### ISSUE TITLE
Initial load takes awhile even on high speed connections

### ISSUE THREAD

**Issue by phongn** [cms-outreach/ispy-webgl#40]
This is kind of annoying for casual users who might just want to look at pretty pictures. 

Maybe use [LZW compression](http://pieroxy.net/blog/pages/lz-string/index.html) and [localStorage](https://github.com/pamelafox/lscache) (cache implementation) to try and reduce initial load times?

**Comment by tpmccauley** [comment]
Yes, the ECAL barrel bit is 16 MB. Some cleverness is needed.

**Comment by msaunby** [comment]
Load takes a long time even when running from localhost.  There are already minified versions of geometry/ee.js and geometry/eb.js  so changing setup.js to load ee.min.js and eb.min.js improves loading time.  Also gzipping these files and calling  
          ispy.getScript("./geometry/eb.min.js.gz"),
           ispy.getScript("./geometry/ee.min.js.gz"),
also helps.   Maybe this won't work everywhere, so I'll not submit a pull request just yet.

**Comment by tpmccauley** [comment]
The naming of the files as "min" is a bit deceptive. The file is eb.min.js is actually not a minified version of eb.js in the sense that whitespace, etc. is removed. It actually contains less content i.e. fewer ECAL crystal geometries, enough to define the borders of the supermodules.

**Comment by tpmccauley** [comment]
addressed in r125 branch with glTF versions of geometry
