### ISSUE TITLE
High CPU/GPU use even on static scenes

### ISSUE THREAD

**Issue by phongn** [cms-outreach/ispy-webgl#41]
With every option checked, I can sustain ~60 FPS. It pegs my GPU, though, on an Nvidia GT 650M. I also get somewhat high CPU use, too (i7 2.6GHz). Can the scene renderer pause when no animation effects are happening? 

My desktop (Intel integrated GPU, i7 3.4GHz) sustains about 25 FPS but I'm pretty sure it's doing software rendering.

**Comment by tpmccauley** [comment]
On the desktop is it doing canvas rendering? It should say so when you click on Settings.

**Comment by phongn** [comment]
It says WebGLRenderer. Huh. The iGPU should be able to smoothly push that many pixels though and at higher framerate unless both browsers are secretly software rendering instead. Or maybe the Intel GPU OpenGL driver really is that terrible. 

I'll check at home with a 'real' GPU to see if I get better performance on Windows.

**Comment by msaunby** [comment]
My experience of this is that it's browser dependent, for example Chrome will update at 60fps if the GPU can cope, but will run it hot.  It's simple to limit. I'll submit a pull request, basically it's this in display.js
ispy.run = function() {
    // remove this - requestAnimationFrame(ispy.run);
    // replace with -
    // Left to run at max speed I get almost 60fps on a Macbook Pro running Chrome.
    // This will cause the fan to come on and drain the battery.
    // So use setTimeout to set the max frame rate.
    var fps = 30;
    setTimeout( function() {
      requestAnimationFrame(ispy.run);
    }, 1000 / fps );
