### ISSUE TITLE
CSC segments missing?

### ISSUE THREAD

**Issue by tpmccauley** [cms-outreach/ispy-webgl#46]
CSC segments seem to be in ig file but not drawn

**Comment by tpmccauley** [comment]
@ptcox I found the problem. The schema for CSCSegments had evolved from V1 to V2 (endcap, station, ring, etc. info was added). The display was only set to draw V1. Easy to fix. Will let you know when done.

**Comment by ptcox** [comment]
Good news. Thanks!

Tim

**Comment by tpmccauley** [comment]
@ptcox done and deployed at http://cern.ch/ispy-webgl
