### ISSUE TITLE
add SiStripClusters

### ISSUE THREAD

**Issue by tpmccauley** [cms-outreach/ispy-webgl#53]

**Comment by tpmccauley** [comment]
@ptcox This was a useful issue to fix as I had to deal with, in some cases, hundreds of hits which I couldn't just draw in a simple-minded way. Doing it a bit smarter I was able to still keep up to 60 fps.

**Comment by ptcox** [comment]
Hey, great! Thanks. I'll try it out later tonight. Doing laundry right now :(

Tim

________________________________
